apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: covid19vis-crawler-patient-cases
  annotations:
    description: "RKI individual cases including statistical information per patient"
spec:
  # run every hour (performs database check before actually fetching data from RKI)
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          containers:
          - name: covid19vis-crawler-patient-cases
            image: registry.dbvis.de/jentner/covid-19-vis/crawler:{{ .Values.sha }}
            imagePullPolicy: Always
            command: ['python']
            args: ['crawl_rki_cases.py']
            env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: database-info
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: database-info
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: database-info
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: database-info
                  key: DB_PASS
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: database-info
                  key: DB_NAME
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: sentry
                  key: SENTRY_DSN
            - name: VERSION
              value: {{ .Values.sha | quote }}
            - name: ENVIRONMENT
              value: {{ .Values.environment | quote }}
            resources:
              requests:
                cpu: 1000m
                memory: 5Gi
              limits:
                cpu: 2000m
                memory: 10Gi
          restartPolicy: Never
          imagePullSecrets:
            - name: regcred-server
