kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-covid19vis-crawler-risklayer-lk
  annotations:
    description: "PVC to store the risklayer excel sheets"
spec:
  storageClassName: rook-cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: crawler-risklayer-lk
  annotations:
    description: "Risklayer spreadhseet download and LK case data extraction"
spec:
  # run every hour (performs database check before actually fetching data from RKI)
  schedule: "0,30 5-21 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 3
      activeDeadlineSeconds: 1200
      template:
        spec:
          containers:
          - name: crawler-risklayer-lk
            image: registry.dbvis.de/jentner/covid-19-vis/crawler:{{ .Values.sha }}
            imagePullPolicy: Always
            command: ['python']
            args: ['crawl_risklayer_lk.py']
            env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: database-info
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: database-info
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: database-info
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: database-info
                  key: DB_PASS
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: database-info
                  key: DB_NAME
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: sentry
                  key: SENTRY_DSN
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: database-info
                  key: API_KEY
            - name: GOOGLE_COOKIES
              valueFrom:
                secretKeyRef:
                  name: google-cookies
                  key: COOKIES
            - name: VERSION
              value: {{ .Values.sha | quote }}
            - name: ENVIRONMENT
              value: {{ .Values.environment | quote }}
            volumeMounts:                                  
            - mountPath: "/var/risklayer_spreadsheets"  
              name: vol-risklayer-spreadsheet-archive 
          volumes:
          - name: vol-risklayer-spreadsheet-archive
            persistentVolumeClaim:
              claimName: pvc-covid19vis-crawler-risklayer-lk    # this must match the name of your PVC
          restartPolicy: Never
          imagePullSecrets:
            - name: regcred-server
