kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: nginx
    {{- include "nginx.annotations" . | nindent 4 }}
spec:
  tls:
    - hosts: 
        - {{ .Values.url }}
      {{- if eq .Values.environment "review-false" }}
      secretName: covis-wildcard
      {{- else }}
      secretName: {{ .Release.Name }}-tls
      {{- end }}
  rules:
    - host: {{ .Values.url }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  name: http
