"""add survstat berlin hack view

Revision ID: 59ad7ea918b6
Revises: cea34abda294
Create Date: 2021-03-17 19:29:52.864284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59ad7ea918b6'
down_revision = 'cea34abda294'
branch_labels = None
depends_on = None


def upgrade():
    op.get_bind().execute("""
    create view survstat_cases_agegroup_berlin_hack
            (ags, year, week, a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11, a12, a13, a14, a15, a16, a17,
             a18, a19, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35, a36, a37, a38,
             a39, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59,
             a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a70, a71, a72, a73, a74, a75, a76, a77, a78, a79, "A80+",
             unbekannt)
as
SELECT survstat_cases_agegroup.ags,
       survstat_cases_agegroup.year,
       survstat_cases_agegroup.week,
       survstat_cases_agegroup.a00,
       survstat_cases_agegroup.a01,
       survstat_cases_agegroup.a02,
       survstat_cases_agegroup.a03,
       survstat_cases_agegroup.a04,
       survstat_cases_agegroup.a05,
       survstat_cases_agegroup.a06,
       survstat_cases_agegroup.a07,
       survstat_cases_agegroup.a08,
       survstat_cases_agegroup.a09,
       survstat_cases_agegroup.a10,
       survstat_cases_agegroup.a11,
       survstat_cases_agegroup.a12,
       survstat_cases_agegroup.a13,
       survstat_cases_agegroup.a14,
       survstat_cases_agegroup.a15,
       survstat_cases_agegroup.a16,
       survstat_cases_agegroup.a17,
       survstat_cases_agegroup.a18,
       survstat_cases_agegroup.a19,
       survstat_cases_agegroup.a20,
       survstat_cases_agegroup.a21,
       survstat_cases_agegroup.a22,
       survstat_cases_agegroup.a23,
       survstat_cases_agegroup.a24,
       survstat_cases_agegroup.a25,
       survstat_cases_agegroup.a26,
       survstat_cases_agegroup.a27,
       survstat_cases_agegroup.a28,
       survstat_cases_agegroup.a29,
       survstat_cases_agegroup.a30,
       survstat_cases_agegroup.a31,
       survstat_cases_agegroup.a32,
       survstat_cases_agegroup.a33,
       survstat_cases_agegroup.a34,
       survstat_cases_agegroup.a35,
       survstat_cases_agegroup.a36,
       survstat_cases_agegroup.a37,
       survstat_cases_agegroup.a38,
       survstat_cases_agegroup.a39,
       survstat_cases_agegroup.a40,
       survstat_cases_agegroup.a41,
       survstat_cases_agegroup.a42,
       survstat_cases_agegroup.a43,
       survstat_cases_agegroup.a44,
       survstat_cases_agegroup.a45,
       survstat_cases_agegroup.a46,
       survstat_cases_agegroup.a47,
       survstat_cases_agegroup.a48,
       survstat_cases_agegroup.a49,
       survstat_cases_agegroup.a50,
       survstat_cases_agegroup.a51,
       survstat_cases_agegroup.a52,
       survstat_cases_agegroup.a53,
       survstat_cases_agegroup.a54,
       survstat_cases_agegroup.a55,
       survstat_cases_agegroup.a56,
       survstat_cases_agegroup.a57,
       survstat_cases_agegroup.a58,
       survstat_cases_agegroup.a59,
       survstat_cases_agegroup.a60,
       survstat_cases_agegroup.a61,
       survstat_cases_agegroup.a62,
       survstat_cases_agegroup.a63,
       survstat_cases_agegroup.a64,
       survstat_cases_agegroup.a65,
       survstat_cases_agegroup.a66,
       survstat_cases_agegroup.a67,
       survstat_cases_agegroup.a68,
       survstat_cases_agegroup.a69,
       survstat_cases_agegroup.a70,
       survstat_cases_agegroup.a71,
       survstat_cases_agegroup.a72,
       survstat_cases_agegroup.a73,
       survstat_cases_agegroup.a74,
       survstat_cases_agegroup.a75,
       survstat_cases_agegroup.a76,
       survstat_cases_agegroup.a77,
       survstat_cases_agegroup.a78,
       survstat_cases_agegroup.a79,
       survstat_cases_agegroup."A80+",
       survstat_cases_agegroup.unbekannt
FROM survstat_cases_agegroup
UNION
SELECT '11000'::character varying             AS ags,
       survstat_cases_agegroup.year,
       survstat_cases_agegroup.week,
       sum(survstat_cases_agegroup.a00)       AS a00,
       sum(survstat_cases_agegroup.a01)       AS a01,
       sum(survstat_cases_agegroup.a02)       AS a02,
       sum(survstat_cases_agegroup.a03)       AS a03,
       sum(survstat_cases_agegroup.a04)       AS a04,
       sum(survstat_cases_agegroup.a05)       AS a05,
       sum(survstat_cases_agegroup.a06)       AS a06,
       sum(survstat_cases_agegroup.a07)       AS a07,
       sum(survstat_cases_agegroup.a08)       AS a08,
       sum(survstat_cases_agegroup.a09)       AS a09,
       sum(survstat_cases_agegroup.a10)       AS a10,
       sum(survstat_cases_agegroup.a11)       AS a11,
       sum(survstat_cases_agegroup.a12)       AS a12,
       sum(survstat_cases_agegroup.a13)       AS a13,
       sum(survstat_cases_agegroup.a14)       AS a14,
       sum(survstat_cases_agegroup.a15)       AS a15,
       sum(survstat_cases_agegroup.a16)       AS a16,
       sum(survstat_cases_agegroup.a17)       AS a17,
       sum(survstat_cases_agegroup.a18)       AS a18,
       sum(survstat_cases_agegroup.a19)       AS a19,
       sum(survstat_cases_agegroup.a20)       AS a20,
       sum(survstat_cases_agegroup.a21)       AS a21,
       sum(survstat_cases_agegroup.a22)       AS a22,
       sum(survstat_cases_agegroup.a23)       AS a23,
       sum(survstat_cases_agegroup.a24)       AS a24,
       sum(survstat_cases_agegroup.a25)       AS a25,
       sum(survstat_cases_agegroup.a26)       AS a26,
       sum(survstat_cases_agegroup.a27)       AS a27,
       sum(survstat_cases_agegroup.a28)       AS a28,
       sum(survstat_cases_agegroup.a29)       AS a29,
       sum(survstat_cases_agegroup.a30)       AS a30,
       sum(survstat_cases_agegroup.a31)       AS a31,
       sum(survstat_cases_agegroup.a32)       AS a32,
       sum(survstat_cases_agegroup.a33)       AS a33,
       sum(survstat_cases_agegroup.a34)       AS a34,
       sum(survstat_cases_agegroup.a35)       AS a35,
       sum(survstat_cases_agegroup.a36)       AS a36,
       sum(survstat_cases_agegroup.a37)       AS a37,
       sum(survstat_cases_agegroup.a38)       AS a38,
       sum(survstat_cases_agegroup.a39)       AS a39,
       sum(survstat_cases_agegroup.a40)       AS a40,
       sum(survstat_cases_agegroup.a41)       AS a41,
       sum(survstat_cases_agegroup.a42)       AS a42,
       sum(survstat_cases_agegroup.a43)       AS a43,
       sum(survstat_cases_agegroup.a44)       AS a44,
       sum(survstat_cases_agegroup.a45)       AS a45,
       sum(survstat_cases_agegroup.a46)       AS a46,
       sum(survstat_cases_agegroup.a47)       AS a47,
       sum(survstat_cases_agegroup.a48)       AS a48,
       sum(survstat_cases_agegroup.a49)       AS a49,
       sum(survstat_cases_agegroup.a50)       AS a50,
       sum(survstat_cases_agegroup.a51)       AS a51,
       sum(survstat_cases_agegroup.a52)       AS a52,
       sum(survstat_cases_agegroup.a53)       AS a53,
       sum(survstat_cases_agegroup.a54)       AS a54,
       sum(survstat_cases_agegroup.a55)       AS a55,
       sum(survstat_cases_agegroup.a56)       AS a56,
       sum(survstat_cases_agegroup.a57)       AS a57,
       sum(survstat_cases_agegroup.a58)       AS a58,
       sum(survstat_cases_agegroup.a59)       AS a59,
       sum(survstat_cases_agegroup.a60)       AS a60,
       sum(survstat_cases_agegroup.a61)       AS a61,
       sum(survstat_cases_agegroup.a62)       AS a62,
       sum(survstat_cases_agegroup.a63)       AS a63,
       sum(survstat_cases_agegroup.a64)       AS a64,
       sum(survstat_cases_agegroup.a65)       AS a65,
       sum(survstat_cases_agegroup.a66)       AS a66,
       sum(survstat_cases_agegroup.a67)       AS a67,
       sum(survstat_cases_agegroup.a68)       AS a68,
       sum(survstat_cases_agegroup.a69)       AS a69,
       sum(survstat_cases_agegroup.a70)       AS a70,
       sum(survstat_cases_agegroup.a71)       AS a71,
       sum(survstat_cases_agegroup.a72)       AS a72,
       sum(survstat_cases_agegroup.a73)       AS a73,
       sum(survstat_cases_agegroup.a74)       AS a74,
       sum(survstat_cases_agegroup.a75)       AS a75,
       sum(survstat_cases_agegroup.a76)       AS a76,
       sum(survstat_cases_agegroup.a77)       AS a77,
       sum(survstat_cases_agegroup.a78)       AS a78,
       sum(survstat_cases_agegroup.a79)       AS a79,
       sum(survstat_cases_agegroup."A80+")    AS "A80+",
       sum(survstat_cases_agegroup.unbekannt) AS unbekannt
FROM survstat_cases_agegroup
WHERE survstat_cases_agegroup.ags::text ~~ '11%'::text
GROUP BY survstat_cases_agegroup.year, survstat_cases_agegroup.week;
    """)


def downgrade():
    op.get_bind().execute("""
        drop view survstat_cases_agegroup_berlin_hack;
    """)
